<a href="https://colab.research.google.com/github/Sanjivkumar100/Emotion_Aware_Production_System/blob/main/emotion_and_prediction_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow
!pip install keras

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.76.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.18.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.1.4)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.5)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras) (3.15.1)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras) (0.18.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras) (0.5.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras) (26.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from optree->keras) (4.15.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)

In [ ]:
import pandas as pd
import numpy as np
import re
import nltk
import pickle

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

nltk.download('stopwords')
stopwords=set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
sad_df=pd.read_csv('/content/drive/MyDrive/Emotional - Product Dataset/sadness-ratings-0to1.train.txt',sep='\t',header=None)
anger_df=pd.read_csv('/content/drive/MyDrive/Emotional - Product Dataset/anger-ratings-0to1.train.txt',sep='\t',header=None)
fear_df=pd.read_csv('/content/drive/MyDrive/Emotional - Product Dataset/fear-ratings-0to1.train.txt',sep='\t',header=None)
joy_df=pd.read_csv('/content/drive/MyDrive/Emotional - Product Dataset/joy-ratings-0to1.train.txt',sep='\t',header=None)

In [ ]:
cols=['id','text','emotion','intensity']
sad_df.columns=cols
anger_df.columns=cols
fear_df.columns=cols
joy_df.columns=cols

nrc_df=pd.concat([sad_df,anger_df,fear_df,joy_df])
nrc_df.reset_index(drop=True,inplace=True)
nrc_df.head()

,id,text,emotion,intensity
0,40000,Depression sucks! #depression,sadness,0.958
1,40001,Feeling worthless as always #depression,sadness,0.958
2,40002,Feeling worthless as always,sadness,0.958
3,40003,My #Fibromyalgia has been really bad lately wh...,sadness,0.946
4,40004,Im think ima lay in bed all day and sulk. Life...,sadness,0.934

In [ ]:
train_go=pd.read_csv('/content/drive/MyDrive/Emotional - Product Dataset/train.tsv',sep='\t')
test_go=pd.read_csv('/content/drive/MyDrive/Emotional - Product Dataset/test.tsv',sep='\t')
dev_go=pd.read_csv('/content/drive/MyDrive/Emotional - Product Dataset/dev.tsv',sep='\t')

go_df=pd.concat([train_go,test_go,dev_go])
go_df.reset_index(drop=True,inplace=True)
go_df.head()

,My favourite food is anything I didn't have to cook myself.,27,eebbqej,"I’m really sorry about your situation :( Although I love the names Sapphira, Cirilla, and Scarlett!",25,eecwqtt,Is this in New Orleans?? I really feel like this is New Orleans.,edgurhb
0,"Now if he does off himself, everyone will thin...",27,ed00q6i,NaN,NaN,NaN,NaN,NaN
1,WHY THE FUCK IS BAYLESS ISOING,2,eezlygj,NaN,NaN,NaN,NaN,NaN
2,To make her feel threatened,14,ed7ypvh,NaN,NaN,NaN,NaN,NaN
3,Dirty Southern Wankers,3,ed0bdzj,NaN,NaN,NaN,NaN,NaN
4,OmG pEyToN iSn'T gOoD eNoUgH tO hElP uS iN tHe...,26,edvnz26,NaN,NaN,NaN,NaN,NaN

In [ ]:
train_go=pd.read_csv('/content/drive/MyDrive/Emotional - Product Dataset/train.tsv',sep='\t', header=None, names=['text', 'labels', 'id'])
test_go=pd.read_csv('/content/drive/MyDrive/Emotional - Product Dataset/test.tsv',sep='\t', header=None, names=['text', 'labels', 'id'])
dev_go=pd.read_csv('/content/drive/MyDrive/Emotional - Product Dataset/dev.tsv',sep='\t', header=None, names=['text', 'labels', 'id'])

go_df=pd.concat([train_go,test_go,dev_go])
go_df.reset_index(drop=True,inplace=True)

In [ ]:
go_df.head()

                                                text labels       id
0  My favourite food is anything I didn't have to...     27  eebbqej
1  Now if he does off himself, everyone will thin...     27  ed00q6i
2                     WHY THE FUCK IS BAYLESS ISOING      2  eezlygj
3                        To make her feel threatened     14  ed7ypvh
4                             Dirty Southern Wankers      3  ed0bdzj

In [ ]:
go_df = go_df[['text','labels']]
go_df["labels"] = go_df["labels"].astype(str)
go_df["primary_label"] = go_df["labels"].apply(lambda x: x.split(",")[0])
go_df["primary_label"] = go_df["primary_label"].astype(int)

In [ ]:
emotion_map = {
0:"admiration", 1:"amusement", 2:"anger", 3:"annoyance",
4:"approval", 5:"caring", 6:"confusion", 7:"curiosity",
8:"desire", 9:"disappointment", 10:"disapproval", 11:"disgust",
12:"embarrassment", 13:"excitement", 14:"fear", 15:"gratitude",
16:"grief", 17:"joy", 18:"love", 19:"nervousness",
20:"optimism", 21:"pride", 22:"realization", 23:"relief",
24:"remorse", 25:"sadness", 26:"surprise", 27:"neutral"
}
go_df["emotion"] = go_df["primary_label"].map(emotion_map)
go_df[["text","emotion"]].head()

                                                text    emotion
0  My favourite food is anything I didn't have to...    neutral
1  Now if he does off himself, everyone will thin...    neutral
2                     WHY THE FUCK IS BAYLESS ISOING      anger
3                        To make her feel threatened       fear
4                             Dirty Southern Wankers  annoyance

In [ ]:
go_df["intensity"] = 0.5

In [ ]:
emotion_df = pd.concat([nrc_df[['text','emotion','intensity']], go_df])
emotion_df.reset_index(drop=True, inplace=True)

In [ ]:
def clean_text(text):

    text = str(text).lower()

    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"@\w+|#\w+", "", text)
    text = re.sub(r"[^a-zA-Z\s]", "", text)

    return text.strip()

emotion_df["clean_text"] = emotion_df["text"].apply(clean_text)

emotion_df.head()

,text,emotion,intensity,labels,primary_label,clean_text
0,Depression sucks! #depression,sadness,0.958,NaN,NaN,depression sucks
1,Feeling worthless as always #depression,sadness,0.958,NaN,NaN,feeling worthless as always
2,Feeling worthless as always,sadness,0.958,NaN,NaN,feeling worthless as always
3,My #Fibromyalgia has been really bad lately wh...,sadness,0.946,NaN,NaN,my has been really bad lately which is not go...
4,Im think ima lay in bed all day and sulk. Life...,sadness,0.934,NaN,NaN,im think ima lay in bed all day and sulk life ...

In [ ]:
def remove_stopwords(text):
  return " ".join([w for w in str(text).split() if w not in stopwords])

emotion_df['clean_text']= emotion_df['clean_text'].apply(remove_stopwords)

In [ ]:
MAX_WORDS = 15000
MAX_LEN = 120

tokenizer = Tokenizer(num_words=MAX_WORDS, oov_token="<OOV>")
tokenizer.fit_on_texts(emotion_df["clean_text"])

X = tokenizer.texts_to_sequences(emotion_df["clean_text"])
X = pad_sequences(X, maxlen=MAX_LEN)

In [ ]:
label_encoder= LabelEncoder()
y_class= label_encoder.fit_transform(emotion_df["emotion"])
scaler= MinMaxScaler()
y_reg= scaler.fit_transform(emotion_df[["intensity"]])

In [ ]:
X_train, X_test, y_class_train, y_class_test, y_reg_train, y_reg_test = train_test_split(
    X, y_class, y_reg,
    test_size=0.2,
    random_state=42
)

In [ ]:
np.save("X_train.npy", X_train)
np.save("X_test.npy", X_test)

np.save("y_class_train.npy", y_class_train)
np.save("y_class_test.npy", y_class_test)

np.save("y_reg_train.npy", y_reg_train)
np.save("y_reg_test.npy", y_reg_test)

In [ ]:
with open("tokenizer.pkl","wb") as f:
    pickle.dump(tokenizer,f)

with open("label_encoder.pkl","wb") as f:
    pickle.dump(label_encoder,f)

In [ ]:
product_df= pd.read_csv('/content/drive/MyDrive/Emotional - Product Dataset/flipkart_com-ecommerce_sample.csv')
product_df.shape

(20000, 15)

In [ ]:
product_df=product_df[[
    'product_name',
    'product_category_tree',
    'description',
    'brand',
    'retail_price',
]]
product_df.dropna(inplace=True)

In [ ]:
def clean_category(cat):
  cat = cat.replace('[','').replace(']','').replace('"','')
  return cat.split('>>')[0].strip().lower()

product_df['category']= product_df['product_category_tree'].apply(clean_category)
product_df

,product_name,product_category_tree,description,brand,retail_price,category
0,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",Key Features of Alisha Solid Women's Cycling S...,Alisha,999.0,clothing
1,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",FabHomeDecor Fabric Double Sofa Bed (Finish Co...,FabHomeDecor,32157.0,furniture
2,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",Key Features of AW Bellies Sandals Wedges Heel...,AW,999.0,footwear
3,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",Key Features of Alisha Solid Women's Cycling S...,Alisha,699.0,clothing
4,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",Specifications of Sicons All Purpose Arnica Do...,Sicons,220.0,pet supplies
...,...,...,...,...,...,...
19995,WallDesign Small Vinyl Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",Buy WallDesign Small Vinyl Sticker for Rs.730 ...,WallDesign,1500.0,baby care
19996,Wallmantra Large Vinyl Stickers Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",Buy Wallmantra Large Vinyl Stickers Sticker fo...,Wallmantra,1429.0,baby care
19997,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",Buy Elite Collection Medium Acrylic Sticker fo...,Elite Collection,1299.0,baby care
19998,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",Buy Elite Collection Medium Acrylic Sticker fo...,Elite Collection,1499.0,baby care
19999,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",Buy Elite Collection Medium Acrylic Sticker fo...,Elite Collection,1499.0,baby care

In [ ]:
product_df['category'].unique()

array(['clothing', 'furniture', 'footwear', 'pet supplies',
       'eternal gandhi super series crystal paper weight...',
       'pens & stationery',
       'bengal blooms rose artificial plant  with pot (3...',
       'bags, wallets & belts', 'home decor & festive needs',
       'automotive', 'tools & hardware',
       "vishudh printed women's straight kurta",
       "vishudh printed women's anarkali kurta",
       'buildtrack pir wireless motion sensor - one swit...',
       'skayvon summersible single phase pump controller...',
       "masara solid women's straight kurta",
       'skayvon submersibble three phase pump controller...',
       'behringer xenyx 502 analog sound mixer',
       "noor embroidered women's straight kurta",
       "libas printed women's a-line kurta",
       "libas printed women's anarkali kurta", 'sports & fitness',
       'home furnishing', 'baby care', 'mobiles & accessories',
       'food & nutrition', 'toys & school supplies', 'jewellery',
       'cellbazaar blackberry 8520 white lcd lcd (yit-562)',
       'dressberry gold synthetic  clutch',
       'mast & harbour black synthetic  clutch',
       "sisel printed poly cotton women's stole",
       'knight ace kraasa sports running shoes, cycling ...',
       "indistar self design viscose women's stole",
       'glacier running shoes', 'dressberry black synthetic  clutch',
       'asics gel-cumulus 17 running shoes',
       'mast & harbour gold synthetic  clutch',
       'asics gel-kayano 22 running shoes',
       'dressberry orange synthetic  clutch',
       'dressberry green synthetic  clutch', 'escan lace up',
       "nine maternity wear women's fit and flare dress",
       'kitchen & dining', 'beauty and personal care', 'home & kitchen',
       'computers', 'watches', 'cameras & accessories',
       'anand archies girls flats', 'anand archies girls wedges',
       'prime printed 8 seater table cover (multicolor, ...',
       'health & personal care appliances',
       'speedwav 240437 sun shade for hyundai i10 (dashb...',
       "vitamins solid baby girl's basic shorts", 'gaming',
       'home improvement', 'sumo baby walker (red)',
       "kombee girl's printed red, pink top & capri set",
       'newgen tech eo-hs3303 218 wired headset (white)',
       'automation & robotics',
       'k&p dr.ambedkar large 04 showpiece  -  19 cm (po...',
       'k&p lord ganesha large 03 showpiece  -  19 cm (p...',
       'adidas ind pro thi gua thigh guard (white, blue,...',
       'bootwale bellies',
       'clickforsign avoid contanimation wash your hands...',
       'treppe bellies', 'kanvas bellies', 'klaur melbourne bellies',
       'clickforsign vehicles parked illegally will be t...',
       'clickforsign sound horn before entering emergenc...',
       "kem flow gold skinny fit baby girl's blue jeans",
       'carbanao chrome grill chevrolet cruze car grill ...',
       'oddy rs 1.5 x 2 100 sheets self stick reposition...',
       'synergy sfjb0105 grocery bag (blue)',
       'shopoj white paper sky lantern (80 cm x 34 cm, p...',
       "supermod men's brief", 'sunglasses',
       "lilliput top baby girl's  combo",
       'frabjous german silver rings for women alloy zir...',
       'zevrr sterling silver swarovski zirconia platinu...',
       'rasav jewels yellow gold diamond 18 k ring',
       'royal seal creations 40 st color silver zircon n...',
       'home entertainment',
       "anasazi casual 3/4 sleeve solid women's top",
       'inventure retail nail cutter',
       "fabpoppy printed women's jumpsuit",
       'power smart quick charging pack for pan cgr-du-2...',
       'gking hand stiched steering cover for maruti ert...',
       'gm power mate 4 strip surge protector (white)',
       'shrih sh-0192 wired usb flexible keyboard (red)',
       "threads & pals full sleeve printed, solid men's ...",
       "threads & pals full sleeve self design men's swe...",
       'gking hand stiched steering cover for renault sc...',
       'power smart quick charging pack for pan cgr-d28 ...',
       'xy decor cotton sofa cover (white pack of 6)',
       'favourite bikerz 3514 rad air filter ionic air f...',
       "little stars girl's a-line multicolor dress",
       'wearable smart devices',
       'the crazy me 1 compartments eco-friendly leather...',
       "laser x checkered men's boxer (pack of 4)",
       "e'hiose girl's leggings (pack of 6)",
       'lucky thailand gl/ lg30 glass (300 ml, clear, pa...',
       'ocean gp/pyramid glass (300 ml, clear, pack of 12)',
       'wella elements leight weight renewing conditione...',
       'pu-good women flats', 'olvin aviator sunglasses',
       "tsg breeze printed women's round neck multicolor...",
       'pout brass bangle', 'classyworld brass cufflink (silver-01)',
       "hans men's crew length socks",
       "timberlake slim fit fit women's brown jeans",
       'olvin oval sunglasses',
       'urban girl foundation brush (pack of 12)',
       'feet flow women flats', 'jazz eyewears over-sized sunglasses',
       "miss wow slim fit women's blue jeans",
       'dilan jewels alloy zircon 18k yellow gold bangle...',
       'smart traders women wedges', "clovia women's full coverage bra",
       'olvin wayfarer sunglasses',
       "privatelifes masterpiece women's push-up bra",
       'coirfit single coir mattress', "clovia women's t-shirt bra",
       "spa culture fit fit women's black jeans",
       "run of luck solid women's round neck dark blue t...",
       'say uv sterilizer solid filter cartridge (0, pac...',
       'urban girl foundation brush (pack of 7)',
       "legmark slim fit women's light blue jeans",
       'siyas collection lac cubic zirconia bangle set (...',
       "dassler slim fit women's multicolor jeans",
       "piftif women's sports bra", 'remson india women flats',
       "killys men's solid no show socks", 'indilego women flats',
       'firangi cotton, polyester free floor mat firangi...',
       "timberlake slim fit fit women's red jeans",
       "starsy solid women's round neck green t-shirt",
       "oly two fit fit women's black jeans",
       'olvin rectangular sunglasses', "soie fashion women's sports bra",
       "auraa men's, women's solid no show socks",
       "e-fresh boy's brief (pack of 5)",
       "timberlake slim fit fit women's blue jeans",
       'newgen tech eo-hs3303 179 wired headset (white)',
       "attitude printed women's round neck black t-shirt",
       'kalpaveda copper bowl (gold, pack of 1)', 'walkline slippers',
       'd&d women flats', "e-fresh baby boy's brief (pack of 10)",
       'newgen tech eo-hs3303 58 wired headset (white)',
       "ajaero slim fit women's dark blue jeans",
       "ruhi's creations cotton floral king sized double...",
       'say thread wounded candle 10\\ set of 4 pcs solid...',
       "the cotton company solid women's polo neck pink ...",
       'samprada modern art tapestry (black, pink)',
       'naaz dart game board game',
       "oly two fit fit women's dark blue jeans",
       "camey men's quarter length socks",
       "fourgee slim fit women's blue jeans",
       'classyworld brass cufflink (grey-02)',
       "viral girl women's full coverage bra",
       'wellon fittings set (16 pieces) for ro water pur...',
       'urban girl foundation brush (pack of 10)',
       'amita home furnishing cotton printed single beds...',
       'impala alloy cufflink (white)',
       "ruhi's creations polyester silk blend cartoon ki...",
       'naaz 2 in 1 paper quilling board game',
       "starsy printed women's round neck black t-shirt",
       "fly u slim fit fit women's brown jeans",
       'crafty hands kutchchi mirrorwork tapestry (maroon)',
       "tadd men's, women's ankle length socks",
       "dolz slim fit fit women's brown jeans",
       'shrih toe & foot protector pain relief pad (pack...',
       "londonhouze printed women's round neck grey t-shirt",
       "legmark slim fit women's blue jeans",
       'linzina fashions lin-hoss-1.5 faucet set',
       "soie fashion women's full coverage bra",
       "clovia women's plunge bra", 'foot candy women flats',
       'amita home furnishing cotton floral single bedsh...',
       "883 police full sleeve solid men's jacket",
       'style world women flats', 'just wow women flats',
       'smart traders women flats',
       "ruhi's creations cotton cartoon king sized doubl...",
       'sj bushnell 122/1000m binoculars (36 mm, black)',
       'sj barstel 56m / 1000m binoculars (30 mm, black)',
       'sj comet zoom dpsi binoculars (30 mm, black)',
       'pia international 10x70x70 with zoom sakura bino...',
       'shopoj purple paper sky lantern (80 cm x 34 cm, ...',
       'car vastra 1pcs car vastra honda beige backrest ...',
       'shopoj yellow paper sky lantern (80 cm x 34 cm, ...',
       'shopoj multicolor paper sky lantern (80 cm x 34 ...',
       'sj bushnell 119m / 1000 binoculars (36 mm, black)',
       "fifo bottom women's  combo",
       'himmlisch 20503 car bottle holder (plastic)',
       'v&g professional hd-37 hair dryer (red)',
       'anuradha art stylish hair clip (blue)',
       'shonaya printed bhagalpuri art silk sari',
       'anuradha art stylish hair clip (black)',
       'jusf2 black color hair band (multicolor)',
       'sonaxo men running shoes',
       'koie  battery - for samsung 7562 premium quality...',
       'oem 170774 bike side stand', 'kittens boys flats',
       'autokraftz optimum locking device for bajaj puls...',
       "galloway skinny fit women's jeans",
       'dremel 2615.023.132 plastic friction work bench ...', 'eyewear',
       'abeez boys, men, girls (black, pack of 1)',
       'joyra heart sterling silver swarovski crystal, s...',
       "blm casual printed women's kurti",
       "smart denim solid women's white denim shorts",
       'atv pouch for acer liquid z330 (steel blue)',
       "be 13 printed boy's round neck t-shirt (pack of 2)",
       'taurus black & white lace up',
       'abhinl fashion cotton printed semi-stitched salw...',
       "ufo self design round neck casual girl's sweater",
       "lgrl women's leggings", "breakbounce men's vest",
       "ufo full sleeve solid girl's jacket",
       'balaji exports bottled wine cooler (9 bottles)',
       'siemens 5sl betagard 5sl mcb (1)',
       'remax rm-10000 remax vanguard 10000mah 10000 mah...',
       'boreal roller brush', 'srajanaa sr114 travel shaving kit (black)',
       "selfcare women's thong panty (pack of 3)",
       'sugandh vatika 24 natural masala, sandal incense...',
       'arial morris women flats', 'zikrak exim women wedges',
       'zixtro bug (black, backpack)',
       "new darling women's printed top & pyjama set",
       "rajeshfashion women's leggings",
       "united colors of benetton girl's trousers",
       'srpc baoer starwalker executive rollerball pen g...',
       'kraft seeds rosemary herb (pack of 5) seed (75 p...',
       'autoplus m ap15 arm sleeve (black)',
       'autoplus m ap18 arm sleeve (black)',
       'kraft seeds thyme herbs seed (200 per packet)',
       'kraft seeds dill herb seed (50 per packet)',
       "leading lady women's camisole", "yo baby girl's trousers",
       'therise md0005 wired headset (pink)',
       'nut khut embroidered kurta & churidar',
       "vinenzia printed winter men's gloves",
       'planet waves woodstock strap (multicolor)',
       'speedwav 216456 manual rear view mirror (right, ...',
       'speedwav 216510 manual rear view mirror (right, ...',
       'speedwav 216552 manual rear view mirror (right, ...',
       'speedwav 186136 manual rear view mirror (right, ...',
       'small toes bellies',
       "easies solid single breasted casual men's blazer",
       'clovia lingerie set',
       'speedwav 186926 royal enfield 350 twin spark led...',
       'speedwav 186879 bajaj pulsar 200 ns dts-i led in...',
       'household supplies', "pazel slim fit men's jeans",
       'smart traders girls bellies',
       'corcepts universal tablet hd ultra clear transpa...',
       'areon luxurious fragrance long lasting car,home,...'],
      dtype=object)

In [ ]:
def clean_text(text):
  text= str(text).lower()
  text= re.sub(r"http\S+", "", text)
  text= re.sub(r"[^a-zA-Z\s]","",text)
  return text.strip()

def stopword_remove(text):
  return " ".join([w for w in str(text).split() if w not in stopwords])

product_df["clean_description"] = product_df["description"].apply(clean_text)
product_df["clean_description"] = product_df["clean_description"].apply(remove_stopwords)

In [ ]:
category_map = {

    "fashion": ["clothing", "footwear", "bags", "jewellery", "watches"],

    "electronics": ["mobiles", "computers", "gaming", "cameras", "home entertainment"],

    "home": ["home", "furniture", "kitchen", "home furnishing", "home decor"],

    "fitness": ["sports", "fitness"],

    "beauty": ["beauty", "personal care"],

    "kids": ["baby care", "toys"],

    "automotive": ["automotive"],

    "stationery": ["pens", "stationery"]
}

def map_category(cat):

    cat = str(cat).lower()

    for main_cat, keywords in category_map.items():
        if any(keyword in cat for keyword in keywords):
            return main_cat

    return "other"
product_df["normalized_category"] = product_df["category"].apply(map_category)

In [ ]:
product_df["normalized_category"].value_counts()

normalized_category
fashion        7230
home           2209
electronics    1795
automotive     1010
other           784
kids            558
beauty          199
stationery      174
fitness         111
Name: count, dtype: int64

In [ ]:
emotion_product_map = {

    "joy": ["fashion","electronics","fitness"],

    "sadness": ["home","beauty","stationery"],

    "anger": ["fitness","electronics"],

    "fear": ["home","beauty"]
}

def recommend_prodcuts(emotion):
  cats=emotion_product_map.get(emotion.lower(),[])
  return product_df[
      product_df["normalized_category"].isin(cats)
      ][["product_name","normalized_category","brand","retail_price"]]

In [ ]:
recommend_prodcuts("joy").head()

,product_name,normalized_category,brand,retail_price
0,Alisha Solid Women's Cycling Shorts,fashion,Alisha,999.0
2,AW Bellies,fashion,AW,999.0
3,Alisha Solid Women's Cycling Shorts,fashion,Alisha,699.0
6,Alisha Solid Women's Cycling Shorts,fashion,Alisha,1199.0
8,"dilli bazaaar Bellies, Corporate Casuals, Casuals",fashion,dilli bazaaar,699.0

In [ ]:
product_df.to_csv("processed_flipkart_products.csv", index=False)